name: Build and publish Docker image; Update manifest repo

env:
  CONFIG_REPO: test_config

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "test"
    tags:
      - 'v*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.memory.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/test_image
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Interjobs output declaration
        id: memory
        run: echo "tag=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT" 
        shell: bash

  update-config:
    runs-on: ubuntu-latest
    needs: build-docker-image
    env:
      TAG: ${{ needs.build-docker-image.outputs.tag }}
    steps:
      - run: |
          git config --global user.email actions@github.com && git config --global user.name Github Actions
          git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO.git
          cd $CONFIG_REPO
          git checkout test
          sed -i 's/${{ secrets.DOCKERHUB_USERNAME }}\/test_image:.*/${{ secrets.DOCKERHUB_USERNAME }}\/test_image:${{ env.TAG }}/g' config/deployment.yaml
          sed -i 's/test-image-.*/test-image-${{ env.TAG }}/g' config/deployment.yaml
          echo ${{ env.TAG }}
          cat config/deployment.yaml
          git add . && git commit -m "Updated to ${{ env.TAG }}" &&  git push
