name: Build and publish Docker image; Update manifest repo

env:
  CONFIG_REPO: test_config

on:
  push:
    branches:
      - "main"
      - "test"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: domintr/test_image
          tags: |
            type=semver,pattern={{version}},value=0.0.0

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  update-config:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - run: |
          git config --global user.email actions@github.com && git config --global user.name Github Actions
          git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO.git
          cd $CONFIG_REPO
          git checkout test
          sed -i '21s/TAG/${{ steps.meta.outputs.tags }}/;22s/TAG/${{ steps.meta.outputs.tags }}/' config/deployment.yaml
          git add . && git commit -m "Updated to ${{ steps.meta.outputs.tags }}" &&  git push
